#!/opt/rocks/bin/python

import os, sys, pwd

from rocks.solid import term_userps

if len(sys.argv) > 1 :
    if sys.argv[1] == '-h' :
        print >> sys.stderr, 'Usage: %s <user1> <user2> ...' % sys.argv[0]
        sys.exit(1)
    user_list = sys.argv[1:]
else :
    user_list = []

term_userps(user_list)
