#!/opt/rocks/bin/python

import sys, os, pwd

from rocks.solid.ipc import cleanipcs

if len(sys.argv) >= 2 :
    if sys.argv[1] == '-h' :
        print >> sys.stderr, 'Usage: %s [sem|shm] [user1] [user2] ...' % sys.argv[0]
        sys.exit(1)
    ipc_list = [sys.argv[1]]
else :
    ipc_list = []

if len(sys.argv) >= 3 :
    user_list = sys.argv[2:]
else :
    user_list = []

cleanipcs(ipc_list, user_list)
