#!/usr/bin/env python

import sys, os, pwd

known_system_users = ['fluent', 'accelrys', 'maya', 'autodesk', 'alias']

def cleanipcs(ipc_list = [], user_list = []) :
    if not ipc_list :
        ipc_list = ['sem', 'shm']
    for ipc in ipc_list :
        if ipc == 'sem' :
            ipc_opt = '-s'
        elif ipc == 'shm' :
            ipc_opt = '-m'
        ipcs = os.popen('ipcs -c ' + ipc_opt)
        id_list = []
        while 1 :
            line = ipcs.readline()
            if not line : break
            try :
                int(line[0])
            except ValueError :
                continue
            ipc_data = line.split()
            uid = pwd.getpwnam(ipc_data[2])[2]
            if uid < 500 or ipc_data[2] in known_system_users :
                continue
            if user_list :
                if ipc_data[2] not in user_list :
                    continue
            id_list.append(ipc_data[0])
        ipcs.close()
        if id_list :
            opt_str = ' ' + ipc_opt + ' '
            options = opt_str + opt_str.join(id_list)
            os.system('ipcrm ' + options)

if len(sys.argv) >= 2 :
    if sys.argv[1] == '-h' :
        print >> sys.stderr, 'Usage: %s [sem|shm] [user1] [user2] ...' % sys.argv[0]
        sys.exit(1)
    ipc_list = [sys.argv[1]]
else :
    ipc_list = []

if len(sys.argv) >= 3 :
    user_list = sys.argv[2:]
else :
    user_list = []

cleanipcs(ipc_list, user_list)
