#!/opt/rocks/bin/python

import sys

import solid.ps as ps

if len(sys.argv) > 1 :
    if sys.argv[1] == '-h' :
        print >> sys.stderr, 'Usage: %s <user1> <user2> ...' % sys.argv[0]
        sys.exit(1)
    user_list = sys.argv[1:]
else :
    user_list = []

ps.term_userps(user_list)
